spring:
  application:
    name: edu-security
  security:
    user:
      password: password
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5450}/${DB_NAME:postgres}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 600000
      pool-name: PostgresHikariPool
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml


logging:
  level:
    org:
      springframework:
        security: TRACE
        web:
          authentication:
            UsernamePasswordAuthenticationFilter: TRACE