spring:
  application:
    name: edu-security
  security:
    user:
      password: password

logging:
  level:
    org:
      springframework:
        security: TRACE
        web:
          authentication:
            UsernamePasswordAuthenticationFilter: TRACE