spring:
  application:
    name: edu-security

logging:
  level:
    org:
      springframework:
        security: TRACE
        web:
          authentication:
            UsernamePasswordAuthenticationFilter: TRACE